Fix shellcheck warnings

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -1,10 +1,12 @@
-#
-# ~/.bashrc
-#
+# shellcheck shell=bash
 
 # If not running interactively, don't do anything
 [[ $- != *i* ]] && return
 
-for file in ${HOME}/.rc.d/*.sh; do
-	. "${file}"
+for file in "${HOME}"/.rc.d/*.sh; do
+  # shellcheck disable=SC1090
+  if ! . "${file}"; then
+    echo "failed to source: ${file}"
+    break
+  fi
 done
diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -1,10 +1,12 @@
-#
-# ~/.zshrc
-#
+# shellcheck disable=SC2148
 
 autoload -Uz compinit && compinit
 autoload -U +X bashcompinit && bashcompinit
 
-for file in ${HOME}/.rc.d/*.sh; do
-	. "${file}"
+for file in "${HOME}"/.rc.d/*.sh; do
+  # shellcheck disable=SC1090
+  if ! . "${file}"; then
+    echo "failed to source: ${file}"
+    break
+  fi
 done
